name: Status Checks Demo

on:
  pull_request:
    branches: [ main ]
  push:

permissions:
  contents: read

jobs:
  lintj:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lint
        run: |
          echo "Running fake lint..."
          echo ${{secrets.PWDNEW}}
          exit 0   # change to 1 to cause failure

  testsj:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Pretend we ran pytest"
          exit 0   # or exit 1 to fail this job

  securityj:
    name: sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SAST simulation
        run: |
          echo "Checking for vulnerabilities..."
          exit 1   # fail this with exit 1
